### ISSUE TITLE
open tabs in random order

### ISSUE THREAD

**Issue by flow14** [ericfinn/TodaysPages#10]
Hey Eric! Great job, thank you!
After my long, happy and fulfilled relationship with morning coffee, who suddenly just disappeared, there's with Today's Pages only one thing I'm missing from that time (besides the great coffee cup icon):
To be able to **open** the **tabs** of the day **in random order**. There was a setting for this in morning coffee. And I loved this, as it was part of the fight against boredom in my daily routines.

**Comment by ericfinn** [comment]
Thanks for the feedback! And will do, this was one of the things I liked about Morning Coffee myself.
Prerequisite: #12

**Comment by ericfinn** [comment]
0.3.0 is live with this change.
