### ISSUE TITLE
Clicking on icon results in no action

### ISSUE THREAD

**Issue by pagosajoe** [ericfinn/TodaysPages#15]
I'm rating it a 5-star add on, however, when I restart Firefox (57.0.2 64 bit) , then click the toolbar image, nothing happens. In the bookmark listing, all the web pages I'd like to see are there for each day. Running Windows 10, latest update, version 1703, build 15063.786.

Thanks for developing a Coffee Cup replacement! I'll be patient....

**Comment by ericfinn** [comment]
Hey, thanks for posting here. I'd like to get some more information. Can you check the contents of `Other Bookmarks > Today's Pages` and tell me what you see, and the number of bookmarks in each folder inside the `Today's Pages` folder?

**Comment by pagosajoe** [comment]
Hi Eric,

You're welcome!  Hope this helps.  The UMTWHFS folders have 29 pages in 
each of them.  Let me know if you need anything else! Merry Christmas!

Joe

**Comment by pagosajoe** [comment]
Hi Eric,

Forgot to include this image...



Joe

**Comment by pagosajoe** [comment]
The latest Firefox update - FF V 57.0.3 64 bit - seems to have corrected 
the issue!  Thanks for your offer - it's working great now!

Joe

**Comment by ericfinn** [comment]
Very odd. I never was able to reproduce the issue, but I'm glad to hear
it's fixed!
