### ISSUE TITLE
Site Management

### ISSUE THREAD

**Issue by max221** [ericfinn/TodaysPages#9]
The way this installed doesn't seem to match your description. Under "Other Bookmarks" is "Todays Pages" followed by U M T W H F S. These folder are empty, except "U"--following the folders are every URL. I'm assuming the fully populated folder "U" is Sunday. Thanks!

![todays pages](https://user-images.githubusercontent.com/750232/32992152-014f8728-cd0d-11e7-8969-8e00f9281064.jpg)

**Comment by ericfinn** [comment]
Woah, that's bad. Thanks for reporting it!

**Comment by ericfinn** [comment]
I'm having trouble reproducing this issue - all the sites are going into the proper day's folders as I'd expect.
Can you tell me the version of Today's Pages you're running, along with your Firefox version and OS?

**Comment by max221** [comment]
I’m a bit embarrassed to say why this may be… I’ve been seeking replacements for legacy add-ons before switching to FF 57. So this was installed on FF 56.02 (64bit), which may well explain this.

The version of Today’s Pages is 0.2.0, and I’m running Windows 10 64bit.

I’ve manually moved my URLs into the proper folders so I can use the add-on (by the way—brilliant, and thank you!)

Max

**Comment by ericfinn** [comment]
One of the reviews gave me the missing bit of info: this issue only occurred on first use. When creating the day folders (U, M, T, etc), only Sunday's would be properly recorded.
